default: &default
  adapter: postgresql
  encoding: unicode
  
pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sweater_weather_development

test:
  <<: *default
  database: sweater_weather_test

production:
  <<: *default
  database: sweater_weather_development
